server:
  port: 8080
  ssl:
    enabled: true
    key-alias: spring
    key-store: src/main/resources/saml/keystore.jks
    key-store-password: secret

security:
  saml2:
      metadata-url: https://dev-166769.oktapreview.com/app/exkegdlni412a2TQB0h7/sso/saml/metadata
  